name: pizza_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_fonts: ^6.1.0
  provider: ^6.1.5+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg_splash.png
    - assets/images/promo.png
    - assets/images/cheese_pizza.png
    - assets/images/chicken_pizza.png
    - assets/images/mushroom_pizza.png
    - assets/images/pepperoni_pizza.png
    - assets/images/pineapple_pizza.png
    - assets/images/pizza.png
    - assets/images/zaitun_pizza.png
    - assets/images/cola.png
    - assets/images/juice_orange.png
    - assets/images/lemon_squash.png
    - assets/images/lemontea.png
    - assets/images/bg_splash1.png
    - assets/lottie/pizza_box_order.json
    


